# Copyright (c) 2024 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""import ops"""
import functools
import importlib
import inspect
import os
import re
import sys

import paddle

from fastdeploy.utils import llm_logger as logger

# Cached list of op names from fastdeploy_ops_pd_.so.
# Populated on first load, reused for subsequent calls.
_PD_OP_NAMES = None

# Global flag: has fastdeploy_ops_pd_.so been loaded via load_op_meta_info_and_register_op?
# Set on first successful load, prevents re-loading (which would crash PaddlePaddle).
_PD_SO_LOADED = False


def import_custom_ops(package, module_name, global_ns):
    """
    Imports custom operations from a specified module within a package and adds them to a global namespace.

    Args:
        package (str): The name of the package containing the module.
        module_name (str): The name of the module within the package.
        global_ns (dict): The global namespace to add the imported functions to.
    """
    # Load custom ops from fastdeploy_ops_pd_.so (DeepGEMM build).
    # This .so contains all ops including get_token_penalty_multi_scores,
    # gptq_marlin_repack, etc.
    pd_loaded = _load_pd_ops(package, module_name, global_ns)

    if not pd_loaded:
        # pd_.so not available — fallback to fastdeploy_ops.so if it exists
        try:
            module = importlib.import_module(module_name, package=package)
            functions = inspect.getmembers(module)
            for func_name, func in functions:
                if func_name.startswith("__") or func_name == "_C_ops":
                    continue
                logger.debug(f"Import {func_name} from {package}")
                try:
                    global_ns[func_name] = func
                except Exception as e:
                    logger.warning(f"Failed to import op {func_name}: {e}")

        except Exception as e:
            logger.warning(f"Ops of {package} import failed, it may be not compiled. {e}")

    preprocess_static_op(global_ns)


def _extract_op_names_from_py(pd_so_path):
    """Extract op names from the companion fastdeploy_ops.py file.

    The .py file (generated by PaddlePaddle's build system) contains Python
    wrapper functions named static_op_* that call _C_ops._run_custom_op().
    We extract these names to know which ops to create wrappers for.
    """
    try:
        py_path = os.path.join(os.path.dirname(pd_so_path), 'fastdeploy_ops.py')
        # Also check __init__.py which may contain the op wrappers
        init_path = os.path.join(os.path.dirname(pd_so_path), '__init__.py')
        for candidate_path in [py_path, init_path]:
            if os.path.exists(candidate_path):
                op_names = []
                with open(candidate_path, 'r') as f:
                    for line in f:
                        m = re.match(r'^def (static_op_\w+)\(', line)
                        if m:
                            op_names.append(m.group(1))
                if op_names:
                    logger.debug(f"Extracted {len(op_names)} op names from {candidate_path}")
                    return op_names
    except Exception as e:
        logger.debug(f"Failed to extract op names from .py: {e}")
    return []


def _find_pd_so(package):
    """Find fastdeploy_ops_pd_.so in various locations."""
    pkg_path = package.replace('.', '/')
    curdir = os.path.dirname(os.path.abspath(__file__))
    fd_root = os.path.join(curdir, '..')  # FastDeploy root

    search_dirs = [
        # Installed location: next to fastdeploy_ops.py/fastdeploy_ops.so
        os.path.join(fd_root, pkg_path),
        # Source location: custom_ops/third_party/DeepGEMM/
        os.path.join(fd_root, 'custom_ops', 'third_party', 'DeepGEMM'),
        # Source location: custom_ops/
        os.path.join(fd_root, 'custom_ops'),
    ]

    for search_dir in search_dirs:
        if not os.path.isdir(search_dir):
            continue
        # Check directly in the directory
        candidate = os.path.join(search_dir, 'fastdeploy_ops_pd_.so')
        if os.path.exists(candidate):
            return candidate
        # Check in versioned subdirectories (e.g., fastdeploy_ops_80/)
        for entry in os.listdir(search_dir):
            entry_path = os.path.join(search_dir, entry)
            if os.path.isdir(entry_path) and entry.startswith('fastdeploy_ops'):
                candidate = os.path.join(entry_path, 'fastdeploy_ops_pd_.so')
                if os.path.exists(candidate):
                    return candidate
    return None


def _load_pd_ops(package, module_name, global_ns):
    """Load custom ops from fastdeploy_ops_pd_.so.

    Returns True if ops were loaded successfully, False otherwise.
    """
    global _PD_SO_LOADED, _PD_OP_NAMES

    # Global guard: if pd_.so was already loaded (by cpu/gcu/gpu module),
    # skip the load_op_meta_info_and_register_op call — calling it twice
    # crashes PaddlePaddle with "meta info register failed".
    if _PD_SO_LOADED:
        # Still populate wrappers in this namespace
        for op_name in (_PD_OP_NAMES or []):
            short_name = op_name.removeprefix("static_op_")
            if short_name not in global_ns:
                global_ns[short_name] = _make_op_fn(op_name)
            if op_name not in global_ns:
                global_ns[op_name] = _make_op_fn(op_name)
        return True

    pd_so_path = _find_pd_so(package)
    if pd_so_path is None:
        logger.debug("fastdeploy_ops_pd_.so not found, skipping")
        return False

    # Check if ops are already available in this namespace
    if global_ns.get('get_token_penalty_multi_scores') is not None:
        logger.debug("PD ops already available in namespace, skipping load")
        return True

    try:
        # Prevent the ops module's __bootstrap__() from running during import.
        # If __bootstrap__() runs, it will load fastdeploy_ops_pd_.so again,
        # causing op registration conflicts.
        _block_bootstrap(module_name, package)

        # Load the .so and register ops with PaddlePaddle (only once globally).
        paddle.utils.cpp_extension.load_op_meta_info_and_register_op(pd_so_path)
        _PD_SO_LOADED = True

        # Create wrappers for all known op names, regardless of return value.
        if _PD_OP_NAMES is None:
            _PD_OP_NAMES = _extract_op_names_from_py(pd_so_path)

        added = 0
        for op_name in _PD_OP_NAMES:
            short_name = op_name.removeprefix("static_op_")
            if short_name not in global_ns:
                global_ns[short_name] = _make_op_fn(op_name)
                added += 1
            if op_name not in global_ns:
                global_ns[op_name] = _make_op_fn(op_name)

        logger.info(f"Loaded {len(_PD_OP_NAMES)} ops from {pd_so_path}, added {added} wrappers for {package}")
        return True

    except Exception as e:
        logger.warning(f"Failed to load fastdeploy_ops_pd_.so: {e}")
        return False
    finally:
        _unblock_bootstrap()


def _make_op_fn(op_name):
    """Create a wrapper function that calls a registered PaddlePaddle custom op."""
    def _op_fn(*args, **kwargs):
        return paddle._C_ops._run_custom_op(op_name, *args, **kwargs)
    return _op_fn


_PD_BOOTSTRAP_BLOCKED = False
_PD_BOOTSTRAP_BLOCK_KEY = None


def _block_bootstrap(module_name, package):
    """Prevent the ops module's __bootstrap__() from running during import.

    Inserts a dummy module into sys.modules at the resolved module path so that
    importlib.import_module() returns the dummy instead of loading the real .py
    (which would call __bootstrap__() and re-register ops).
    """
    global _PD_BOOTSTRAP_BLOCKED, _PD_BOOTSTRAP_BLOCK_KEY
    _PD_BOOTSTRAP_BLOCKED = True
    # Resolve full dotted path: e.g. "fastdeploy.model_executor.ops.gpu.fastdeploy_ops.fastdeploy_ops"
    full_path = (package + module_name).lstrip('.')
    _PD_BOOTSTRAP_BLOCK_KEY = full_path

    class _DummyOpsModule:
        pass
    sys.modules[full_path] = _DummyOpsModule()


def _unblock_bootstrap():
    """Remove the dummy module block."""
    global _PD_BOOTSTRAP_BLOCKED, _PD_BOOTSTRAP_BLOCK_KEY
    _PD_BOOTSTRAP_BLOCKED = False
    if _PD_BOOTSTRAP_BLOCK_KEY and _PD_BOOTSTRAP_BLOCK_KEY in sys.modules:
        mod = sys.modules[_PD_BOOTSTRAP_BLOCK_KEY]
        if mod.__class__.__name__ == '_DummyOpsModule':
            del sys.modules[_PD_BOOTSTRAP_BLOCK_KEY]
    _PD_BOOTSTRAP_BLOCK_KEY = None


def rename_imported_op(old_name, new_name, global_ns):
    """
    Renames an imported operation in the global namespace.

    Args:
        old_name (str): The original name of the operation in the global namespace.
        new_name (str): The new name to be given to the operation.
        global_ns (dict): The global namespace where the operation is stored.
    """
    if old_name not in global_ns:
        return
    global_ns[new_name] = global_ns[old_name]
    del global_ns[old_name]


def wrap_unified_op(original_cpp_ext_op, original_custom_op):
    """
    Wrap a static operator into a unified operator with runtime dispatching.
    Args:
        original_cpp_ext_op: Original C++ extension operator function.
        original_custom_op: Original custom operator function.
    """
    try:

        @paddle.jit.marker.unified
        @functools.wraps(original_custom_op)
        def unified_op(*args, **kwargs):
            if paddle.in_dynamic_mode():
                res = original_cpp_ext_op(*args, **kwargs)
                if res is None:
                    return None
                # TODO(DrRyanHuang): Remove this if when we align the implementation of custom op and C++ extension
                if isinstance(res, list) and len(res) == 1:
                    return res[0]
                return res
            return original_custom_op(*args, **kwargs)

    except:
        unified_op = None
        logger.warning("Paddle version not support JIT mode.")
    return unified_op


def preprocess_static_op(global_ns):
    """
    Transforms operator/function references in the global namespace based on the presence of 'static_op_' prefixes.

    Args:
        global_ns (dict): The global namespace (typically globals()) to modify.
        flag (bool): Determines transformation behavior.
    """
    static_op_prefix = "static_op_"
    static_op_names = [k for k in global_ns if k.startswith(static_op_prefix)]

    for static_op_name in static_op_names:
        op_name = static_op_name.removeprefix(static_op_prefix)
        if op_name not in global_ns:
            global_ns[op_name] = global_ns[static_op_name]
            continue

        original_cpp_ext_op = global_ns[op_name]
        original_custom_op = global_ns[static_op_name]
        global_ns[op_name] = wrap_unified_op(original_cpp_ext_op, original_custom_op)
